"use strict"

export const Hello = "Hello"
export const GetProfiles = "GetProfiles"
export const StartGame = "StartGame"
export const LoadGame = "LoadGame"
export const ExitGame = "ExitGame"
export const Solve = "Solve"
export const GetProgressStatus = "GetProgressStatus"
export const GetSolutionVariants = "GetSolutionVariants"
export const SetLetter = "SetLetter"
export const AddWord = "AddWord"
export const AddUsedWord = "AddUsedWord"
export const GetNextStepInfo = "GetNextStepInfo"
export const AddToBlacklist = "AddToBlacklist"
export const AddToWhitelist = "AddToWhitelist"